/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tetris;

import com.google.gson.reflect.TypeToken;
import java.util.ArrayList;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

/**
 *
 * @author John
 */
public class RankingForm extends javax.swing.JFrame {
    
    private MainForm mainWindow;
    private final String MATCHFILEPATH = "./src/Data/Ranking.txt";
    private Gson gson = new Gson();
    
    public RankingForm(MainForm mainWindow) {
        initComponents();
        this.mainWindow = mainWindow;
        mostrarRanking();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        titleForm = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaRanking = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/background2.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(500, 400));
        background.setMinimumSize(new java.awt.Dimension(500, 400));
        background.setPreferredSize(new java.awt.Dimension(500, 400));

        titleForm.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        titleForm.setForeground(new java.awt.Color(255, 255, 255));
        titleForm.setText("Ranking");

        btnBack.setText("Volver");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txaRanking.setEditable(false);
        txaRanking.setBackground(new java.awt.Color(36, 36, 36));
        txaRanking.setColumns(20);
        txaRanking.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txaRanking.setForeground(new java.awt.Color(255, 255, 255));
        txaRanking.setRows(5);
        txaRanking.setBorder(null);
        jScrollPane1.setViewportView(txaRanking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleForm)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(222, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titleForm)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        this.mainWindow.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed
    
    ArrayList arrRankings;
    
    private void mostrarRanking(){
        loadRanking();
        if (arrRankings == null)
            txaRanking.setText("El ranking está vació");
        else{
        txaRanking.setText("");
        txaRanking.setText("Nombre \tTiempo \tPuntaje");
        for (int i = 0; i < arrRankings.size(); i++) {
            txaRanking.setText(txaRanking.getText() + "\n" + (i+1) + ".  " + arrRankings.get(i).toString());
        }
        }
    }
    
    public void loadRanking(){
        String matchesStr = FileManager.readFile(MATCHFILEPATH);
        if(matchesStr != ""){
                this.arrRankings = gson.fromJson(matchesStr, new TypeToken<ArrayList<Ranking>>(){}.getType()); // se carga la lista de partidas
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titleForm;
    private javax.swing.JTextArea txaRanking;
    // End of variables declaration//GEN-END:variables
}
